#!/usr/bin/env julia
#
# Verification script for the Odin BLAS QR update implementation
# This script reads the data files generated by the Odin regression example
# and verifies the results using Julia's LinearAlgebra module.
#

using LinearAlgebra
using DelimitedFiles
using Printf

println("=" ^ 60)
println("Julia Verification of Odin QR Update Results")
println("=" ^ 60)
println()

# Helper function to read CSV files
function read_matrix(filename)
    return readdlm(filename, ',', Float64)
end

function read_vector(filename)
    return vec(readdlm(filename, Float64))
end

# Tolerance for comparisons
const TOL = 1e-8

# Track overall success
all_passed = true

# ============================================================================
# 1. Verify Initial Model Fit
# ============================================================================
println("--- 1. Initial Model Fit ---")

try
    X_initial = read_matrix("examples/X_initial.csv")
    y_initial = read_vector("examples/y_initial.csv")
    beta_odin = read_vector("examples/beta_initial.csv")

    # Compute OLS using Julia's backslash operator (uses QR internally)
    beta_julia = X_initial \ y_initial

    println("Odin coefficients:  ", round.(beta_odin, digits=6))
    println("Julia coefficients: ", round.(beta_julia, digits=6))

    max_diff = maximum(abs.(beta_odin - beta_julia))
    @printf("Max difference: %.2e\n", max_diff)

    if max_diff < TOL
        println("✓ PASSED: Initial model fit matches")
    else
        println("✗ FAILED: Initial model fit differs")
        global all_passed = false
    end

    # Also verify using explicit QR
    Q, R = qr(X_initial)
    beta_qr = R \ (Q' * y_initial)
    @printf("QR explicit max diff: %.2e\n", maximum(abs.(beta_odin - beta_qr)))

catch e
    println("Error reading initial model files: ", e)
    global all_passed = false
end

println()

# ============================================================================
# 2. Verify Column Deletion
# ============================================================================
println("--- 2. Column Deletion (Remove Column 3, 1-indexed) ---")

try
    X_delcol = read_matrix("examples/X_delcol.csv")
    y_initial = read_vector("examples/y_initial.csv")
    beta_delcol_update = read_vector("examples/beta_delcol_update.csv")
    beta_delcol_recompute = read_vector("examples/beta_delcol_recompute.csv")

    # Compute OLS in Julia
    beta_julia = X_delcol \ y_initial

    println("Odin (QR update):   ", round.(beta_delcol_update, digits=6))
    println("Odin (recomputed):  ", round.(beta_delcol_recompute, digits=6))
    println("Julia coefficients: ", round.(beta_julia, digits=6))

    diff_update = maximum(abs.(beta_delcol_update - beta_julia))
    diff_recompute = maximum(abs.(beta_delcol_recompute - beta_julia))
    diff_odin = maximum(abs.(beta_delcol_update - beta_delcol_recompute))

    @printf("Odin update vs Julia:    %.2e\n", diff_update)
    @printf("Odin recompute vs Julia: %.2e\n", diff_recompute)
    @printf("Odin update vs recompute: %.2e\n", diff_odin)

    if diff_update < TOL && diff_recompute < TOL
        println("✓ PASSED: Column deletion results match")
    else
        println("✗ FAILED: Column deletion results differ")
        global all_passed = false
    end

catch e
    println("Error in column deletion verification: ", e)
    global all_passed = false
end

println()

# ============================================================================
# 3. Verify Column Addition
# ============================================================================
println("--- 3. Column Addition (Insert at position 4, 1-indexed) ---")

try
    X_addcol = read_matrix("examples/X_addcol.csv")
    y_initial = read_vector("examples/y_initial.csv")
    beta_addcol_update = read_vector("examples/beta_addcol_update.csv")
    beta_addcol_recompute = read_vector("examples/beta_addcol_recompute.csv")

    # Compute OLS in Julia
    beta_julia = X_addcol \ y_initial

    println("Odin (QR update):   ", round.(beta_addcol_update, digits=6))
    println("Odin (recomputed):  ", round.(beta_addcol_recompute, digits=6))
    println("Julia coefficients: ", round.(beta_julia, digits=6))

    diff_update = maximum(abs.(beta_addcol_update - beta_julia))
    diff_recompute = maximum(abs.(beta_addcol_recompute - beta_julia))
    diff_odin = maximum(abs.(beta_addcol_update - beta_addcol_recompute))

    @printf("Odin update vs Julia:    %.2e\n", diff_update)
    @printf("Odin recompute vs Julia: %.2e\n", diff_recompute)
    @printf("Odin update vs recompute: %.2e\n", diff_odin)

    if diff_update < TOL && diff_recompute < TOL
        println("✓ PASSED: Column addition results match")
    else
        println("✗ FAILED: Column addition results differ")
        global all_passed = false
    end

catch e
    println("Error in column addition verification: ", e)
    global all_passed = false
end

println()

# ============================================================================
# 4. Verify Row Addition
# ============================================================================
println("--- 4. Row Addition (Add 3 new observations) ---")

try
    X_addrows = read_matrix("examples/X_addrows.csv")
    y_addrows = read_vector("examples/y_addrows.csv")
    beta_addrows = read_vector("examples/beta_addrows.csv")

    # Compute OLS in Julia
    beta_julia = X_addrows \ y_addrows

    println("Odin coefficients:  ", round.(beta_addrows, digits=6))
    println("Julia coefficients: ", round.(beta_julia, digits=6))

    diff = maximum(abs.(beta_addrows - beta_julia))
    @printf("Max difference: %.2e\n", diff)

    if diff < TOL
        println("✓ PASSED: Row addition results match")
    else
        println("✗ FAILED: Row addition results differ")
        global all_passed = false
    end

    # Verify the QR factorization
    Q, R = qr(X_addrows)
    println("\nJulia R matrix (first 5x5):")
    display(round.(R[1:min(5, size(R,1)), 1:min(5, size(R,2))], digits=4))
    println()

catch e
    println("Error in row addition verification: ", e)
    global all_passed = false
end

println()

# ============================================================================
# Additional Verification: Residual Norms
# ============================================================================
println("--- Residual Norm Verification ---")

try
    X_initial = read_matrix("examples/X_initial.csv")
    y_initial = read_vector("examples/y_initial.csv")
    beta_initial = read_vector("examples/beta_initial.csv")

    resid_odin = norm(X_initial * beta_initial - y_initial)
    beta_julia = X_initial \ y_initial
    resid_julia = norm(X_initial * beta_julia - y_initial)

    @printf("Odin residual norm:  %.6f\n", resid_odin)
    @printf("Julia residual norm: %.6f\n", resid_julia)

    if abs(resid_odin - resid_julia) < TOL
        println("✓ PASSED: Residual norms match")
    else
        println("✗ WARNING: Residual norms differ (but may still be valid)")
    end

catch e
    println("Error in residual verification: ", e)
end

println()

# ============================================================================
# Summary
# ============================================================================
println("=" ^ 60)
if all_passed
    println("✓ ALL VERIFICATIONS PASSED")
else
    println("✗ SOME VERIFICATIONS FAILED")
end
println("=" ^ 60)

# ============================================================================
# Bonus: Show condition numbers and numerical properties
# ============================================================================
println("\n--- Numerical Properties ---")

try
    X_initial = read_matrix("examples/X_initial.csv")
    @printf("Condition number of X: %.2f\n", cond(X_initial))
    @printf("Matrix dimensions: %d × %d\n", size(X_initial)...)
    @printf("Rank: %d\n", rank(X_initial))
catch e
    println("Error computing numerical properties: ", e)
end
